spring.datasource.url: jdbc:h2:mem:testdb
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: username
spring.datasource.password: password
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

spring.h2.console.enabled: true

server:
  #8092
  port: ${PORT} 

spring:
  # Schema that the application assumes that the security table is in.
  jpa:
    properties:
      hibernate:
        default_schema: ${RIDESHARE_POSTGRES_1909_SCHEMA}
  # Postgres DB location and login info.
  datasource:
    url: jdbc:postgresql://${RIDESHARE_POSTGRES_1909_URL}:5432/postgres?
    username: ${RIDESHARE_POSTGRES_1909_USERNAME}
    password: ${RIDESHARE_POSTGRES_1909_PASSWORD}
