server:
  #8092
  port: ${PORT}

spring:
  # Schema that the application assumes that the security table is in.
  jpa:
    properties:
      hibernate:
        default_schema: ${RIDESHARE_POSTGRES_1909_SCHEMA}
        
        database-platform: org.hibernate.dialect.H2Dialect
  # Postgres DB location and login info.
  datasource:
    #url: jdbc:postgresql://${RIDESHARE_POSTGRES_1909_URL}:5432/postgres?
    username: ${RIDESHARE_POSTGRES_1909_USERNAME}
    password: ${RIDESHARE_POSTGRES_1909_PASSWORD}
    
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    