-- ENSURE THAT YOU RUN THIS IN THE CORRECT DATABASE AND SCHEMA.
CREATE TABLE public.SECURITY (
USER_ID identity PRIMARY KEY,
EMAIL TEXT NOT NULL UNIQUE,
PASSOWRD TEXT NOT NULL,
ROLES TEXT,
)

-- CONVIENIENCE STATEMENT FOR MINOR TABLE ALTERATIONS IF NECESSARY.
--drop table "security";

-- DO NOT USE THE BELOW INSERTS, THEY WILL NOT HAVE THE PASSWORDS ENCODED CORRECTLY.
-- THIS SECTION HAS BEEN KEPT TO SHOW AN EXAMPLE OF THE COLUMNS.
-- VIEW "DbInit.java" IN THE APPLICATION TO EDIT WHAT ROWS ARE INITIALLY ADDED.
--insert into "security" values (1, 'test@test.com', 'pass', 'NULL');
--insert into "security" values (2, 'user@user.com', 'pass', 'USER');
--insert into "security" values (3, 'admin@admin.com', 'pass', 'ADMIN');